### ISSUE TITLE
integration with GlobusAuthenticator

### ISSUE THREAD

**Issue by zonca** [globus/globus-jupyter-notebooks#10]
is there any plan to have this integrated with `GlobusAuthenticator` (<https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/globus.py>) so that once you login with Globus you can also do transfers from the Notebook?

**Comment by jaswilli** [comment]
Hi @zonca,

Sorry for the slow response, I didn't see the notification when you opened this issue.

I don't think it's likely we'd integrate that plugin into this particular notebook because we use it as a reference/teaching tool, part of which includes how to do the Globus Auth authentication flow.

I wasn't involved in the creation of the jupyterhub plugin but if you're interested in using it I can connect you with the people on the team who worked on it.
